# Generated by Django 3.1.3 on 2022-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fitbit_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='salesPredict',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('yyyymm', models.CharField(db_column='yyyymm', max_length=20)),
                ('sales_amt', models.IntegerField(db_column='sales_amt', default=0)),
                ('sales_predict', models.IntegerField(db_column='sales_predict', default=0)),
            ],
            options={
                'db_table': 'sales_predict',
                'managed': False,
            },
        ),
    ]
